version: '3'

services:
  app:
    build: .
    entrypoint: sh -c "npm install && npm run start:dev"
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    depends_on:
      - db
  
  db:
    image: mongo:6.0.2
    ports:
      - 27017:27017
    volumes:
      - ./.docker/dbdata:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
  
  db_test:
    image: mongo:6.0.2
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    tmpfs:
      - /data/db
